### ISSUE TITLE
Where are you boot parmaters stored in lick?

### ISSUE THREAD

**Issue by Randall-Glass** [noryb009/lick#19]
Need more documentation for lick.

I am wanting to make puppy linux to think it's using a flash drive.
Need to change the boot parameters from pmedia=atahd to pmedia=ataflash.

Where are you boot parmaters stored.

**Comment by noryb009** [comment]
It should either be in `C:/lickgrub.cfg` or `C:/lickmenu.lst`. Only one of these files will exist, depending on your computer.

* If you found the file `C:/lickgrub.cfg`, you will see a line similar to `linux /path-to/vmlinuz psubdir="path" pfix=fsck`. You will want to add your option here, like `linux /path-to/vmlinuz psubdir="path" pfix=fsck pmedia=ataflash`.

* If you found the file `C:/lickmenu.lst`, you should see something similar to `kernel "/path-to/vmlinuz" psubdir="path" pfix=fsck`. You will want to add your new parameter to that line, so it would look like `kernel "/path-to/vmlinuz" psubdir="path" pfix=fsck pmedia=ataflash`

You will only need to do one of the two steps above, depending on which one of the two files are on your computer. If you have trouble editing the files in Windows, try editing them while in linux.

**Comment by Randall-Glass** [comment]
Mine is  C:/lickgrub.cfg.

Is C:/lickgrub.cfg a grub 2 menu file?

And does puppy linux get it's boot parameters from it?

For example can I do pmedia=usbflash to control how often the save is written to? (pupsave=13)

__________________________
Best Regards!

Randall Glass
7505 Campbell's Corner Rd
McLeansboro, IL 62859
Ph: 618-728-4589
http://RadioTelephoneTutor.com

--------------------------------------------
On Sun, 11/12/17, Lukas Lorimer <notifications@github.com> wrote:

 Subject: Re: [noryb009/lick] Where are you boot parmaters stored in lick? (#19)
 To: "noryb009/lick" <lick@noreply.github.com>
 Cc: "Randall Glass" <rlglass2@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, November 12, 2017, 2:06 AM
 
 It should either be in
 C:/lickgrub.cfg or
 C:/lickmenu.lst. Only one of these files will
 exist, depending on your computer.
 
 
 If you found the file C:/lickgrub.cfg, you
 will see a line similar to linux /path-to/vmlinuz
 psubdir="path" pfix=fsck. You will want to
 add your option here, like linux /path-to/vmlinuz
 psubdir="path" pfix=fsck
 pmedia=ataflash.
 
 
 If you found the file C:/lickmenu.lst, you
 should see something similar to kernel
 "/path-to/vmlinuz" psubdir="path"
 pfix=fsck. You will want to add your new parameter to
 that line, so it would look like kernel
 "/path-to/vmlinuz" psubdir="path"
 pfix=fsck pmedia=ataflash
 
 
 You will only need to do one of the two steps above,
 depending on which one of the two files are on your
 computer. If you have trouble editing the files in Windows,
 try editing them while in linux.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by noryb009** [comment]
Yes, it's a grub 2 menu file, and yes, puppy linux gets its boot parameters from the text on the "linux" line. You are correct, you should be able to add pmedia or any other parameter to the "linux" line corresponding to the boot option you select on startup.
