### ISSUE TITLE
on 7 lick best on newest win10 not taking save file

### ISSUE THREAD

**Issue by sadddssdfdff** [noryb009/lick#27]
on 7 lick best on newest win10 not taking save file
but save file saved if i look to my pc in win

i get installed puppies
but just xenial 64 lasttt and xfce xenial 64

they show up at reboot

others some hibernate …. messages

bbut xenials both dont pick up the save file
at reboot

so its always the raw puppy

sad to give up puppy for ever

any idea????????

    

    with wubi 16… unofficial .......ubuntus are working on same laptop win10
    but i like more puppy
 

        i have win 10 newst just bought

https://photos.app.goo.gl/BVV5ySjbj8ZRf8aE2
https://photos.app.goo.gl/OOixsenIuCN4x6gW2

**Comment by noryb009** [comment]
I responded to this [here](http://www.murga-linux.com/puppy/viewtopic.php?p=989449#989449), let's resolve the issue there. Since I'm not getting emails from the forum, if I don't respond on the forum for a day or so, feel free to ping me on this issue.

**Comment by sadddssdfdff** [comment]
thank u great seems to work now answer is there

greatest urr lickkk!!

**Comment by noryb009** [comment]
Good to hear! Closing this now.
