### ISSUE TITLE
Lick not supports windows 10 (64 bit)

### ISSUE THREAD

**Issue by lucky754299** [noryb009/lick#34]
I am trying to install puppy linux using lick latest version on windows 10 64bit system but it is not installing.  it works on 32 bit but not on 64 bit please resolve this issue

**Comment by noryb009** [comment]
What do you mean "it is not installing"? What steps did you take? What error messages do you see?

**Comment by lucky754299** [comment]
First I installed lick loader, then I uploaded puppy linux iso file it is showing not supports 64 bit windows 10. Please check. 
If you have lick setup for 64 bit system please share the link

**Comment by lucky754299** [comment]
"error installing loader!" This type of error is displayed

**Comment by noryb009** [comment]
Do you have BIOS or a UEFI system? You can check [using this](https://www.nextofwindows.com/windows-8-quick-tip-how-to-tell-if-my-windows-is-uefi-booted).

In your BIOS/UEFI, do you have a legacy bootloader enabled? It can be called various things.

**Comment by lucky754299** [comment]
I have checked, it's a Legacy enabled

**Comment by noryb009** [comment]
Can you try turning it to the non-legacy option and trying to install?

**Comment by noryb009** [comment]
@lucky754299 I received another similar bug report, and it seems like Windows changed some of its permissions. You should be able to use [this version of LICK](https://github.com/noryb009/lick/files/5322387/LICK-1.3.3-win32.zip) to successfully get things installed. I'll be releasing a new official version of LICK with these changes soon.

**Comment by AlisterH** [comment]
I had the same issue, and the linked version worked.  I see the next version has been tagged, but GitHub is still showing the previous version as the latest release.  Is there a reason for that?

**Comment by noryb009** [comment]
@AlisterH I have upgraded computers since the last release, and I haven't been able to setup the entire build pipeline (notably NSIS had some issues) and I haven't setup test environments (notably Windows 9x VMs, but also other versions).

**Comment by noryb009** [comment]
@AlisterH I finally got around to testing the package, and have released it: https://github.com/noryb009/lick/releases/latest
