### ISSUE TITLE
Issue on Windows XP Pro SP1 Lick 1.3.3 error: invalid boot.ini

### ISSUE THREAD

**Issue by yahyayness** [noryb009/lick#35]
During the questions cycle, the following error appears at the end of the cycle:
error: invalid boot.ini

Then the sequence restarts

I have been advised to use precise-5.7.1.iso on a 2001 Vaio pcg-gt1 with 192Mb Ram 7.5Gb free space for c: drive install
Lick 1.3.3. 32 bit version

Here's the thread on Puppy forums: https://forum.puppylinux.com/viewtopic.php?f=2&t=791

**Comment by noryb009** [comment]
Can you post the contents of the file `C:\boot.ini` ? If you don't see it in File Explorer, you might need to open an administrator command prompt and run `notepad C:\boot.ini` to view the file.

**Comment by yahyayness** [comment]
There was a single line with a call to grub4dos loader ="Topology Linux
v5.1.0"

Problem solved, sorry and my bad because an old TopologyLinux install
apparently moved the potent boot.ini to another drive root. Because of
that, Lick could not find the proper one, which I solved by copying the one
of my h: drive to c: then re-copying the installed file in c: root to h:
From then on Lick behaves normally.

Thank you so much by the way for this great piece of software, now my Vaio
GT-1 runs Linux seamlessly, I can backup through firewire which was not
possible in XP. I hope to be able to enable the camera and microphone
through either wine or native support in puppy4.3.1

There's a blog for the project, it's a world's first! More here:
https://sonyvaio-gt1.blogspot.com/
Comments and constructive criticism welcome!

François Gabriel Wayenberg

**Comment by noryb009** [comment]
Good to hear you were able to resolve this!
