### ISSUE TITLE
Getting Lick to load .2fs saved Puppy session files at startup

### ISSUE THREAD

**Issue by yahyayness** [noryb009/lick#36]
Hi,
I saw this is obviously possible, but myself and other users can't seem to be able to find how it is done, and what is the syntax. Is it through specifying the saved file in lickmenu.lst ? 

I am sorry to report this as a bug but the documentation on how this is done seems not to be available anymore, and I need this for my technical project to be able to advance: it is great to be able to reboot unchanged when experimenting with settings but now I need these combined so it's getting too time consuming to advance. 

Thanks for your understanding, and thank you in advance.

**Comment by noryb009** [comment]
Providing the `psubdir=directoryPuppyIsIn` option in `lickmenu.lst` should tell puppy to look for the savefile inside the given directory. This is automatically done. Does this not work in a certain puppy version?

**Comment by yahyayness** [comment]
I had to place the user file in the Lick Puppy .iso created directory
manually for Puppy4.3.1 and it solved the issue. I saved the userfile on
another, ext2 partition in order not to risk damaging my other installs due
to the machine dual booting XP is currently not bootable via external media
(I need a cd-rom from the time, either a firewire cd-rw or a pcmcia one).
Slacko5.6-4G on the other side seemed to solve the issue by itself, as I
learnt from the startup indications.

Just to be sure,  can you confirm the syntax directoryPuppyIsIn is in Linux
form?

**Comment by yahyayness** [comment]
I have another issue with Slacko 5.3.3. that I'm testing for meye (Sony Motion Eye) module, suddenly it forgot about the .2fs userfile even after putting it back in the startup directory it is not recognized. My Puppy went for amnesia!

**Comment by noryb009** [comment]
> problem seems to be solved by putting the .2fs saved user file in the same directory, there it is detected again

It sounds like you were able to resolve this :) Closing
