### ISSUE TITLE
Feature: be able to change resolution to 1920x1080

### ISSUE THREAD

**Issue by Randall-Glass** [noryb009/lick#49]
Have run bionicpup64 with no problem with 1920x1080 resolution, in my old 
lenvo PC.

Have a dell optiplex 3080 that that boots Lick's grub in resolution 800x600 mode.

This messes up bionicpup64 so it can't change the resolution to 1920x1080

Suggest that Lick's grub be able to change resolution to various relolutions,
including 1920x1080.

This should be able to fix bionicpup's resolution problem.

**Comment by noryb009** [comment]
You can make the necessary changes to either `C:/lickmenu.lst` (for BIOS systems), or `C:/lickgrub.cfg` (for UEFI systems). LICK cannot get into the business of making a GUI for grub config changes, especially because it uses 2 very different versions of grub.
