### ISSUE TITLE
Lick bug in detecting video driver and setting video resolution.

### ISSUE THREAD

**Issue by Randall-Glass** [noryb009/lick#50]
Reset my bios settings to secure mode.

Did the hash

Did set gfx=1920x1080x32 in the lick config file.

Rebooted to the lick grub boot gui.

Did not do the resolution.

Went to the command line and did videoinfo.

1920x1080x32 is available, but it detects my video as a cirrus CLGD video driver.

My PC has a intel I5 10th generation intergrated graphics card.

Definetly not a cirrus CLGD graphics card.

**Comment by noryb009** [comment]
> Did set gfx=1920x1080x32 in the lick config file.

You haven't specified anything about your system, so I'm not sure if you're using grub2 or grub4dos - I assume the former. `gfx` is not a recognized environment variable by grub2. I think you would want to set `gfxmode` instead, [see this documentation](https://www.gnu.org/software/grub/manual/grub/grub.html#gfxmode).

**Comment by noryb009** [comment]
[Closing](https://github.com/noryb009/lick/issues/54#issuecomment-1079804142)
