### ISSUE TITLE
lickgrub.cfg is a protected in windows & you cannot edit it.

### ISSUE THREAD

**Issue by Randall-Glass** [noryb009/lick#51]
Am using a new leveno P340.

lickgrub.cfg is a protected in windows & you cannot edit it.
One might want the default to be a "puppy linux os.

And move the arrow to windows to go to the windows os.

The big problem is that lickgrub.cfg is a protected in windows & you cannot edit it.

**Comment by Randall-Glass** [comment]
You cannot edit c:/lickgrub.cfg.

Would be nice if one could put lickgrub.cfg on another partition instead.

**Comment by noryb009** [comment]
In Windows, you can only edit the file with a text editor opened as an administrator. A boot-related file should require administrator privileges to edit, so this will not be changed.

You can also edit `lickgrub.cfg` inside Linux without worrying about permissions.

**Comment by Randall-Glass** [comment]
Editing lickgrub.cfg in linux sounds like a good idea.

Here is a link to info grub version less than version 1.06
is valuable to malware.

BootHole GRUB bootloader bug lets hackers hide malware in Linux, Windows
<https://www.bleepingcomputer.com/news/security/boothole-grub-bootloader-bug-lets-hackers-hide-malware-in-linux-windows/>

We don't want any malware messing with linux.

Are you going to release a new version of lick, that contains
grub version 1.06?


-- 
Best Regards!

Randall Glass
http://bicycledefensivedriving.org

**Comment by Randall-Glass** [comment]
Found out you can edit lickgrub.cfg, if you run notepad as administrator.
