### ISSUE TITLE
Compile Lick 1.34 so it stores lickgrub.cfg in a different partition?

### ISSUE THREAD

**Issue by Randall-Glass** [noryb009/lick#52]
How would I go about compiling Lick 1.34 so it stores lick.cfg in a different partition.

And so that it only uses grub4dos.

**Comment by noryb009** [comment]
Please follow [this guide](https://github.com/noryb009/lick/blob/master/DEVELOP.md) to setup a local development environment. You will also need to copy the resources included in the most recent binary release to the `res/` directory, or you can compile them yourself.

`lickgrub.cfg` relates to grub2, but you also say you want to remove it - which of these do you want to do?

**Comment by noryb009** [comment]
[Closing](https://github.com/noryb009/lick/issues/54#issuecomment-1079804142)
