### ISSUE TITLE
Grub VMLinuz not found

### ISSUE THREAD

**Issue by hermayne** [noryb009/lick#58]
Hi! I want to make a dual boot of puppy linux fossapup64-9.5 using Lick alongside my windows10 but when I reboot after the installation, Grub command shows telling need to load kernel first. Then I follow how to load kernel but showing error vmlinuz not found. Please see the attached pics maybe it can help. Any help will be appreciated. Thanks! This is my pc:
Acer Swift 3 Intel UHD 620 graphics
12gb RAM 240gb SSD intel i5
Windows10 Pro

PS.
Secure Boot=Disabled
Fast boot=Disabled
I can boot puppy linux from usb thumb drive

![grub1](https://user-images.githubusercontent.com/113760783/190846814-2e1ed94b-5c50-45b3-87c5-d2e362e4d26b.png)
![grub2](https://user-images.githubusercontent.com/113760783/190846837-636dc1f7-df4d-4730-90fd-3582d33871c1.png)
![grub3](https://user-images.githubusercontent.com/113760783/190846848-75e86ea0-60cd-4672-9dcb-01e7f2fd3e66.png)

**Comment by noryb009** [comment]
It's odd that (hd0,gpt3) is an unknown filesystem. In Windows, can you look for  "Create and format hard disk partitions" in the Start menu, and let me know what File System shows up for the different partitions?

**Comment by hermayne** [comment]
![disk](https://user-images.githubusercontent.com/113760783/190884480-7098b56d-5cba-48aa-a4c5-d47599cfd879.png)

**Comment by noryb009** [comment]
The "BitLocker" encryption on your C drive means that grub can't look into it to find the required files. Unfortunately, this is not a scenario that LICK supports today, and this changes some of the core assumptions of LICK, so it can't really be supported.

I'll close this as won't do. You'll probably have more luck making a partition to install Linux in (however, I'm not sure what the best way to resize your encrypted partition is).
