### ISSUE TITLE
Support for Easy OS image

### ISSUE THREAD

**Issue by don570** [noryb009/lick#63]
Support for Easy OS image

BarryK is using limine now to set up a EXT4 partition 
for Easy OS , but I was wondering if it was possible  to make changes to lick
so it could use an image rather than an ISO .
Limine is dropping EXT4 support
https://github.com/limine-bootloader/limine/commit/7119459b0725bcd77b54167be7558a4d93420ba1
_____________________________________________________________________
A frugal install of Easy OS just requires an EXT4 partition to be created then the transferal of a few files,
https://easyos.org/install/easy-frugal-installation.html#:~:text=In%20the%20ext4%20partition%20of,one%20folder%20in%20the%20partition

**Comment by noryb009** [comment]
While it's possible to do this, this goes beyond what LICK is intended to do, which is a frugal install on a Windows-accessible partition. Notably, this restriction lets us avoid the potential issues that come with partitioning the hard drive, along with the undo steps required when uninstalling. Unfortunately, this means Easy OS is not supported.
